### PR TITLE
Support MacOS

### PR DESCRIPTION
**Pull request by pierreglaser**
This PR aims to add support to MacOS. It includes:

- support for the [choose](https://github.com/chipsenkbeil/choose) fuzzy finder, as `rofi` is not supported on MacOS
- usage of `fswatch` instead of `inotify` for the same above reason.

Depending on what is considered public API, I may have introduced some breaking changes. The CLI interface did not change, but the internals yes, due to some refactoring.

I currently tested it on my MacBook, but not on a linux system -- I may have broken some things along the way. I am going to check this branch on a linux machine ASAP.

cc @gillescastel just in case.

### CODE REVIEW

**Comment by BerryTaylor** [comment]
Hi, it seems not to work on my MacOS with Inkscape the latest version. I used the pip3 and followed your commits to modify main.py,setup.py and replace the rofi.py with picker.py . And the result is like that on the picture:
image

**Comment by pierreglaser** [comment]
IIRC `inotify` is not supported on `MacOS` (I mentioned it in the original PR message). Have you `pip install`-ed the module? It should look for `fswatch` instead at installation step.

**Comment by BerryTaylor** [comment]
Then I pip3 uninstall inotify 
and pip3 setup.py install (with all your commits
brew install fswatch (then I found that I already have installed fswatch  
and I get this 
image

**Comment by pierreglaser** [comment]
Could you do `python3 -m pip install -e path/to/inkscape-figures/` instead of `pip3 setup.py install` to install `inkscape-figures`? I can't reproduce your problem locally.

Also, you might want to check why you have a `command not found: inkscape-figures` error message by `zsh`.

**Comment by pierreglaser** [comment]
Thank you for taking the time to test this branch by the way!

**Comment by BerryTaylor** [comment]
You are welcome, I am also pleased that someone has made this pull request and looking forward to making it work. 
My steps are as following:
First I download your code, whose path is ~/inkscapefigures/inkscape-figures
then I ran: python3 -m pip install -e ~/inkscapefigures/inkscape-figures
then I get this : 
image
And my Inkscape version is 1.1-dev (f9311a1, 2019-12-25).
vim is installed by brew.
I have uninstalled the inotify, and I also had fswatch.
image
Here is my site-package of python3, the Inkscape-figures package seems strange after using your suggestion.

**Comment by pierreglaser** [comment]
Ideally, you can first create a python virtual environment where you do solely an editable install of inkscape-figures:
```sh
python3 -m venv venv/
source venv/bin/activate
python3 -m pip install -e path/to/inkscape-figures
```
If you do this, you won't for sure have an `inkscape-figures` entry in your `site-packages`.

**Comment by pierreglaser** [comment]
Also, what command triggers this error? `pip install -e`? or a bash command triggered by a mapping in vim?

**Comment by BerryTaylor** [comment]
OK, I have followed your advice, and my python is now in (venv) virtual environment.
But the error is still .
This error is triggered by the 'Ctrl-F' mapping in vim ,detail:
let ssssssss = Tex_GetMainFileName(':h')

inoremap <C-f> <Esc>: silent exec '.!inkscape-figures create "'.getline('.').'" "'.ssssssss.'/figures/"'<CR><CR>:w<CR>
nnoremap <C-f> : silent exec '!inkscape-figures edit "'.ssssssss.'/figures/" > /dev/null 2>&1 &'<CR><CR>:redraw!<CR>

"inoremap <C-k> <Esc>: silent exec '.!/home/u/tmath_snippets/geogebra.sh "'.getline('.').'" "'.ssssssss.'/geofigures/"'<CR><CR>:w<CR>
"nnoremap <C-k> : silent exec '!/home/u/tmath_snippets/geogebraedit.sh "'.ssssssss.'/geofigures/" > /dev/null 2>&1 &'<CR><CR>:redraw!<CR>

**Comment by pierreglaser** [comment]
Can you try running `inkscape-figures create test_figure` on bash so that I can see the output?

**Comment by BerryTaylor** [comment]
image

**Comment by pierreglaser** [comment]
Let's move the discussion to my fork so that we don't add too much noise to this thread.

**Comment by BerryTaylor** [comment]
It did work perfectly! I will sort out the steps we figure out the problem later, if you have the same problem just see our conversations please!

**Comment by gillescastel** [comment]
Merging this! Thanks a lot for the pull request, @pierreglaser!

**Comment by pierreglaser** [comment]
No worries. I'll try to be responsive to issues opened here related to MacOS support. Do not hesitate to ping me @gillescastel .

**Comment by BerryTaylor** [comment]
Hi,@pierreglaser
the Inkscape-figures watch command seems strange 
when I run the command, there is not any responses nor log
and of course the svg can not be saved as pdf and pdf_tex automatically

**Pull request merged**
